# Generated by Django 5.2.1 on 2025-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('AT_RISK', 'At Risk'), ('UPCOMING', 'Upcoming'), ('ON_SCHEDULE', 'On Schedule'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAR', 'Aadhar Card'), ('RESUME', 'Resume'), ('PASSPORT', 'Passport'), ('BANK', 'Bank Documents'), ('PF', 'PF Documents'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
