# Generated by Django 5.2.1 on 2025-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_project_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='projects', to='employee.employee'),
        ),
    ]
