# Generated by Django 5.2.1 on 2025-05-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_bankaccount_incometax_insurancepolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometax',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='employee',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='IncomeTax',
        ),
        migrations.DeleteModel(
            name='InsurancePolicy',
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
