# Generated by Django 5.2.1 on 2025-05-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_incometax_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('employment_type', models.CharField(choices=[('INTERN', 'Intern'), ('FULL_TIME', 'Full-Time'), ('CONSULTANT', 'Consultant')], max_length=20)),
                ('joining_date', models.DateField()),
                ('employment_type_at_hiring', models.CharField(choices=[('INTERN', 'Intern'), ('FULL_TIME', 'Full-Time'), ('CONSULTANT', 'Consultant')], max_length=20)),
                ('full_time_conversion_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('title', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('mobile_number', models.CharField(max_length=10)),
                ('insured_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('endorsement_type', models.CharField(choices=[('A', 'A'), ('D', 'D')], max_length=1)),
                ('critical_illness_maternity', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('parking_status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('vehicle_number_plate', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(choices=[('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('FORD', 'Ford'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes'), ('AUDI', 'Audi'), ('HYUNDAI', 'Hyundai'), ('OTHER', 'Other')], max_length=20)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WiFiAccess',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('mobile_number', models.CharField(max_length=10)),
                ('access_card_number', models.CharField(max_length=20)),
            ],
        ),
    ]
