# Generated by Django 5.2.1 on 2025-05-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='allow_edit',
            field=models.BooleanField(default=False),
        ),
    ]
