# Generated by Django 5.2.1 on 2025-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_profileupdaterequest_allow_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_reupload',
            field=models.BooleanField(default=False),
        ),
    ]
