# Generated by Django 5.2.1 on 2025-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_document_allow_reupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='allow_reupload',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
