# Generated by Django 5.2.1 on 2025-05-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_document_allow_reupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_reupload',
            field=models.BooleanField(default=False),
        ),
    ]
