# Generated by Django 5.2.1 on 2025-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_trainingtag_trainingblog_trainingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAR', 'Aadhar Card'), ('RESUME', 'Resume'), ('PASSPORT', 'Passport'), ('BANK', 'Bank Documents'), ('PF', 'PF Documents'), ('PASSBOOK', 'Passbook'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
