# Generated by Django 5.2.1 on 2025-06-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboarding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
