# Generated by Django 5.2.1 on 2025-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employee_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_BACKEND', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('EMAIL_HOST', models.CharField(default='smtp.office365.com', max_length=255)),
                ('EMAIL_PORT', models.PositiveIntegerField(default=587)),
                ('EMAIL_USE_TLS', models.BooleanField(default=True)),
                ('EMAIL_HOST_USER', models.EmailField(max_length=254)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=255)),
                ('DEFAULT_FROM_EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
