# Generated by Django 5.2.1 on 2025-06-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_emailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail/Google Workspace'), ('office365', 'Outlook/Office365'), ('zoho', 'Zoho Mail'), ('sendgrid', 'SendGrid'), ('ses', 'Amazon SES'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
