# Generated by Django 5.2.1 on 2025-06-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_emailsettings_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='addharNo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
