# Generated by Django 5.2.1 on 2025-06-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_bankdetail_insurancepolicy_personaldetail_taxdetail'),
    ]

    operations = [
    ]
