# Generated by Django 5.2.1 on 2025-06-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_education_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
