# Generated by Django 5.2.1 on 2025-06-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_remove_workexperience_employee_delete_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='comments',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='allow_reupload',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee'),
        ),
    ]
