# Generated by Django 5.2.1 on 2025-06-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_jobposting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
