# Generated by Django 5.2.1 on 2025-06-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_alter_project_table_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
