# Generated by Django 5.2.1 on 2025-06-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
