# Generated by Django 5.0.14 on 2025-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_clocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
