# Generated by Django 5.0.14 on 2025-06-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_attendance_auto_clocked_out_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-time_in']},
        ),
    ]
