# Generated by Django 5.0.14 on 2025-06-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_alter_attendance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20),
        ),
    ]
