# Generated by Django 5.0.14 on 2025-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_remove_attendance_overtime_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='auto_clocked_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
