version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: empdb
      POSTGRES_USER: empuser
      POSTGRES_PASSWORD: emppass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn empmanagement.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: 