# Generated by Django 5.0.14 on 2025-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_id_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msuserprofile',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='msuserprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='msuserprofile',
            name='verification_requested_at',
        ),
        migrations.RemoveField(
            model_name='msuserprofile',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='msuserprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='msuserprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
