# Generated by Django 5.0.14 on 2025-06-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_id_management', '0002_remove_msuserprofile_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msuserprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='msuserprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
