# Generated by Django 5.2.1 on 2025-05-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
    ]
