# Generated by Django 5.2.1 on 2025-05-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='destinationEmployeeId',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='requesterId',
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='employee',
        ),
        migrations.DeleteModel(
            name='TimeTrackingConfig',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
