# Generated by Django 5.2.1 on 2025-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
