# Generated by Django 5.2.1 on 2025-05-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_onboarding'),
    ]

    operations = [
    ]
